language: node_js
node_js: --lts # LTS
cache: yarn
before_script:
  - yarn lint
install:
  - yarn install --ignore-scripts # Prevent flow-typed update
script:
  - yarn test --coverage --colors
after_success:
  - codecov
  - yarn build # Prevent before_deploy not being tested in PRs
before_deploy:
  - echo "$CNAME" > build/CNAME
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: build
  skip_cleanup: true
  keep-history: true
  on:
    branch: master
